package model;

// Generated 13 Jul, 2022 2:47:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * DoctorSchedule generated by hbm2java
 */
public class DoctorSchedule implements java.io.Serializable {

	private Integer id;
	private Integer did;
	private String days;
	private String startTime;
	private String endTime;
	private String message;
	private String status;

	public DoctorSchedule() {
	}

	public DoctorSchedule(Integer did, String days, String startTime, String endTime, String message, String status) {
		this.did = did;
		this.days = days;
		this.startTime = startTime;
		this.endTime = endTime;
		this.message = message;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getDays() {
		return this.days;
	}

	public void setDays(String days) {
		this.days = days;
	}

	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return this.endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
