package model;

// Generated 13 Jul, 2022 2:47:01 PM by Hibernate Tools 3.4.0.CR1

/**
 * Patient generated by hbm2java
 */
public class Patient implements java.io.Serializable {

	private Integer id;
	private String fname;
	private String lname;
	private String email;
	private String password;
	private String gender;
	private Long phone;
	private String dob;
	private String address;
	private String disease;

	public Patient() {
	}

	public Patient(String fname, String lname, String email, String password, String gender, Long phone, String dob,
			String address, String disease) {
		this.fname = fname;
		this.lname = lname;
		this.email = email;
		this.password = password;
		this.gender = gender;
		this.phone = phone;
		this.dob = dob;
		this.address = address;
		this.disease = disease;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Long getPhone() {
		return this.phone;
	}

	public void setPhone(Long phone) {
		this.phone = phone;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

}
